server:
  port: 8080
spring:
  application:
    name: springcloud-consumer
eureka:
  client:
    service-url:
      defaultZone: http://eureka7002:7002/eureka,http://eureka7003:7003/eureka,http://eureka7001:7001/eureka
    #register-with-eureka: false
  instance:
    instance-id: springcloud-consumer80
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
#Ribbon配置访问机制
springcloud-book:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RetryRule #查看服务是否存在机制