server:
  port:  7003
#配置eureka服务注册
eureka:
  instance:
    hostname:  spring-eureka7003
  client: #关闭注册服务 防止自己注册自己
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7002:7002,http://eureka7001:7001
